/* ══════════════════════════════════════════════════════════════════
   Vedomostný QUIZ 2026 – Databáza otázok
   Scope: sk = Slovensko, svet = Svet
   Difficulty: junior (1. stupeň ZŠ), level1 (SŠ), level2 (ťažšie)
   ══════════════════════════════════════════════════════════════════ */
const QUESTIONS_DB = [
{id:1001,question:'Kto bol prvý prezident Slovenskej republiky?',answer:'Michal Kováč',category:'dejiny_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1002,question:'V ktorom roku vznikla samostatná Slovenská republika?',answer:'1993',category:'dejiny_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1003,question:'Ako sa volal hrad, kde sa konali korunovácie uhorských kráľov?',answer:'Bratislavský hrad',category:'dejiny_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1004,question:'Kto boli Cyril a Metod?',answer:'Vierozvestci (solúnski bratia)',category:'dejiny_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1005,question:'Ako sa volala prvá slovenská univerzita?',answer:'Univerzita Istropolitana',category:'dejiny_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1006,question:'V ktorom roku bola bitka pri Moháči?',answer:'1526',category:'dejiny_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1007,question:'Kto viedol Slovenské národné povstanie?',answer:'Generál Ján Golian a generál Rudolf Viest',category:'dejiny_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1008,question:'V ktorom roku sa uskutočnilo SNP?',answer:'1944',category:'dejiny_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1009,question:'Kedy vznikla Veľká Morava?',answer:'V 9. storočí (okolo 833)',category:'dejiny_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1010,question:'Kto bol Ľudovít Štúr?',answer:'Kodifikátor spisovnej slovenčiny a národný buditeľ',category:'dejiny_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1011,question:'V ktorom roku boli prijaté Žiadosti slovenského národa?',answer:'1848',category:'dejiny_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1012,question:'Aké knieža založilo Nitrianske kniežatstvo?',answer:'Pribina',category:'dejiny_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1101,question:'Aký je najvyšší vrch Slovenska?',answer:'Gerlachovský štít (2 655 m)',category:'geografia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1102,question:'Aká je najdlhšia rieka Slovenska?',answer:'Váh',category:'geografia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1103,question:'Koľko krajov má Slovensko?',answer:'8',category:'geografia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1104,question:'Aké jazero je najväčšie na Slovensku?',answer:'Veľké Hincovo pleso',category:'geografia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1105,question:'V ktorom pohorí sa nachádza Gerlachovský štít?',answer:'Vysoké Tatry',category:'geografia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1106,question:'Aký štát nesusedí so Slovenskom – Poľsko, Nemecko, Maďarsko?',answer:'Nemecko',category:'geografia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1107,question:'Ako sa volá najväčšia priehrada na Slovensku?',answer:'Oravská priehrada',category:'geografia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1108,question:'V ktorom meste sa nachádza Spišský hrad?',answer:'V blízkosti Spišského Podhradia',category:'geografia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1109,question:'Koľko susedných krajín má Slovensko?',answer:'5 (ČR, Poľsko, Ukrajina, Maďarsko, Rakúsko)',category:'geografia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1110,question:'Aký je najväčší ostrov na Dunaji pri Bratislave?',answer:'Veľký Žitný ostrov',category:'geografia_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1111,question:'Aká je rozloha Slovenska v km²?',answer:'Približne 49 035 km²',category:'geografia_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1201,question:'Aké je hlavné mesto Slovenska?',answer:'Bratislava',category:'krajske_mesta',difficulty:'junior',scope:'sk',type:'normal'},
{id:1202,question:'Krajské mesto východného Slovenska s Dómom sv. Alžbety?',answer:'Košice',category:'krajske_mesta',difficulty:'junior',scope:'sk',type:'normal'},
{id:1203,question:'Ktoré krajské mesto sa nachádza na rieke Nitra?',answer:'Nitra',category:'krajske_mesta',difficulty:'junior',scope:'sk',type:'normal'},
{id:1204,question:'V ktorom krajskom meste je známa zoo?',answer:'Bratislava',category:'krajske_mesta',difficulty:'junior',scope:'sk',type:'normal'},
{id:1205,question:'Krajské mesto pri Oravskej priehrade?',answer:'Žilina',category:'krajske_mesta',difficulty:'level1',scope:'sk',type:'normal'},
{id:1206,question:'Aké krajské mesto má prezývku „slovenský Rím"?',answer:'Nitra',category:'krajske_mesta',difficulty:'level1',scope:'sk',type:'normal'},
{id:1207,question:'Krajské mesto, kde sa nachádza technická univerzita s baníckou tradíciou?',answer:'Banská Bystrica',category:'krajske_mesta',difficulty:'level1',scope:'sk',type:'normal'},
{id:1208,question:'Koľko obyvateľov má približne Bratislava?',answer:'Približne 450 000',category:'krajske_mesta',difficulty:'level2',scope:'sk',type:'normal'},
{id:1209,question:'Ktoré krajské mesto má letisko M. R. Štefánika?',answer:'Bratislava',category:'krajske_mesta',difficulty:'level1',scope:'sk',type:'normal'},
{id:1210,question:'V ktorom krajskom meste sa nachádza Trenčiansky hrad?',answer:'Trenčín',category:'krajske_mesta',difficulty:'junior',scope:'sk',type:'normal'},
{id:1211,question:'Ktoré krajské mesto leží pri sútoku Váhu a Rajčianky?',answer:'Žilina',category:'krajske_mesta',difficulty:'level2',scope:'sk',type:'normal'},
{id:1212,question:'Krajské mesto so známou Starou radnicou a Prezidentským palácom?',answer:'Bratislava',category:'krajske_mesta',difficulty:'level1',scope:'sk',type:'normal'},
{id:1301,question:'Aké zviera žije vo Vysokých Tatrách a je symbolom?',answer:'Kamzík (tatranský)',category:'prirodoveda_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1302,question:'Aký kvet kvitne na jar ako prvý na lúkach?',answer:'Snežienka (alebo krokus)',category:'prirodoveda_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1303,question:'Aký najväčší dravec žije v slovenských horách?',answer:'Medveď hnedý',category:'prirodoveda_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1304,question:'Koľko nôh má hmyz?',answer:'6',category:'prirodoveda_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1305,question:'Čo je fotosyntéza?',answer:'Proces, kedy rastlina premieňa CO₂ a vodu na kyslík a glukózu pomocou svetla',category:'prirodoveda_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1306,question:'Aký typ horniny je žula?',answer:'Vyvretá (magmatická) hornina',category:'prirodoveda_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1307,question:'Aký endemit sa vyskytuje len v Tatrách?',answer:'Kamzík tatranský',category:'prirodoveda_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1308,question:'Koľko národných parkov má Slovensko?',answer:'9',category:'prirodoveda_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1309,question:'Aký je rozdiel medzi ihličnatým a listnatým lesom?',answer:'Ihličnaté stromy majú ihličie (smrek, jedľa), listnaté majú listy (buk, dub)',category:'prirodoveda_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1310,question:'Aké sú tri skupenstvá vody?',answer:'Pevné (ľad), kvapalné (voda), plynné (para)',category:'prirodoveda_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1401,question:'Koľko je 7 × 8?',answer:'56',category:'matematika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1402,question:'Koľko minút má jedna hodina?',answer:'60',category:'matematika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1403,question:'Koľko strán má štvorec?',answer:'4',category:'matematika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1404,question:'Koľko je 100 ÷ 4?',answer:'25',category:'matematika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1405,question:'Aký je obvod štvorca so stranou 5 cm?',answer:'20 cm',category:'matematika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1406,question:'Koľko stupňov má pravý uhol?',answer:'90°',category:'matematika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1407,question:'Aký je obsah kruhu s polomerom 3? (použite π ≈ 3,14)',answer:'Približne 28,26',category:'matematika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1408,question:'Čo je Pytagorova veta?',answer:'a² + b² = c² (v pravouhlom trojuholníku)',category:'matematika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1409,question:'Koľko je odmocnina z 144?',answer:'12',category:'matematika_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1410,question:'Koľko je 15 % z 200?',answer:'30',category:'matematika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1501,question:'Aké mesto má ŠPZ „BA"?',answer:'Bratislava',category:'spz_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1502,question:'Aké mesto má ŠPZ „KE"?',answer:'Košice',category:'spz_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1503,question:'Aké mesto má ŠPZ „ZA"?',answer:'Žilina',category:'spz_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1504,question:'Aké mesto má ŠPZ „BB"?',answer:'Banská Bystrica',category:'spz_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1505,question:'Aké mesto má ŠPZ „TN"?',answer:'Trenčín',category:'spz_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1506,question:'Aké mesto má ŠPZ „NR"?',answer:'Nitra',category:'spz_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1507,question:'Aké mesto má ŠPZ „PO"?',answer:'Prešov',category:'spz_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1508,question:'Aké mesto má ŠPZ „TT"?',answer:'Trnava',category:'spz_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1509,question:'Aké mesto má ŠPZ „PP"?',answer:'Poprad',category:'spz_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1510,question:'Aké mesto má ŠPZ „MT"?',answer:'Martin',category:'spz_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1511,question:'Aké mesto má ŠPZ „LM"?',answer:'Liptovský Mikuláš',category:'spz_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1512,question:'Aké mesto má ŠPZ „DT"?',answer:'Detva',category:'spz_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1601,question:'Kto napísal rozprávku „O dvanástich mesiacikoch"?',answer:'Božena Němcová (z povestí)',category:'literatura_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1602,question:'Kto je autor básne „Mor ho!"?',answer:'Samo Chalupka',category:'literatura_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1603,question:'Kto napísal „Kráľ Svätopluk"?',answer:'Ján Hollý',category:'literatura_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1604,question:'Ktorý slovenský spisovateľ napísal „Jožko Púčik a jeho kariéra"?',answer:'Ľudo Ondrejov',category:'literatura_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1605,question:'Kto je autor románu „Živý bič"?',answer:'Milo Urban',category:'literatura_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1606,question:'Ako sa volá najznámejšia kniha Pavla Országha Hviezdoslava?',answer:'Hájnikova žena',category:'literatura_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1607,question:'Kto napísal „Tri gaštanové kone"?',answer:'Margita Figuli',category:'literatura_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1608,question:'Aký žáner je „Detvan" od Andreja Sládkoviča?',answer:'Veršovaná skladba (básnická)',category:'literatura_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1609,question:'Kto bol Pavol Dobšinský?',answer:'Zberateľ slovenských ľudových rozprávok',category:'literatura_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1610,question:'Kto napísal „Marína"?',answer:'Andrej Sládkovič',category:'literatura_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1701,question:'Koľko samohlások má slovenčina?',answer:'16 (krátke + dlhé + dvojhlásky)',category:'slovensky_jazyk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1702,question:'Aký pád odpovedá na otázku „Koho? Čoho?"?',answer:'Genitív (2. pád)',category:'slovensky_jazyk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1703,question:'Koľko pádov má slovenčina?',answer:'6',category:'slovensky_jazyk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1704,question:'Čo je synonymum?',answer:'Slovo s rovnakým alebo podobným významom',category:'slovensky_jazyk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1705,question:'Aký slovný druh je slovo „rýchlo"?',answer:'Príslovka',category:'slovensky_jazyk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1706,question:'Koľko je v slovenčine vzorových slov pre podstatné mená?',answer:'12',category:'slovensky_jazyk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1707,question:'Čo je antonymum?',answer:'Slovo s opačným významom',category:'slovensky_jazyk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1708,question:'Čo je prirovnanie?',answer:'Jazykový prostriedok, kde sa niečo prirovnáva k niečomu (ako, sťa)',category:'slovensky_jazyk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1709,question:'Kto kodifikoval súčasný slovenský pravopis?',answer:'Ľudovít Štúr (1843, neskôr upravený)',category:'slovensky_jazyk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1710,question:'Aký je rozdiel medzi „i" a „y" v slovenčine?',answer:'Zapisujú sa podľa pravopisných pravidiel (vybrané slová)',category:'slovensky_jazyk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1801,question:'Kto bol Milan Rastislav Štefánik?',answer:'Slovenský vedec, diplomat a generál, spoluzakladateľ Česko-Slovenska',category:'osobnosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1802,question:'Kto je Peter Sagan?',answer:'Slovenský profesionálny cyklista, majster sveta',category:'osobnosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1803,question:'Kto bol Alexander Dubček?',answer:'Slovenský politik, tvár Pražskej jari 1968',category:'osobnosti_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1804,question:'Kto je Zuzana Čaputová?',answer:'Prvá žena – prezidentka SR (2019-2024)',category:'osobnosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1805,question:'Kto bol Andrej Hlinka?',answer:'Slovenský kňaz a politik, bojovník za práva Slovákov',category:'osobnosti_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1806,question:'Kto bol Jozef Murgaš?',answer:'Vynálezca, priekopník bezdrôtovej telegrafie',category:'osobnosti_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1807,question:'Kto bola Lucia Popp?',answer:'Svetoznáma slovenská operná speváčka (soprán)',category:'osobnosti_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1808,question:'Kto je Juraj Jánošík v slovenskej kultúre?',answer:'Legendárny zbojník, symbol odporu proti nespravodlivosti',category:'osobnosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1809,question:'Kto bol Ján Jessenius?',answer:'Lekár, vykonal prvú verejnú pitvu v Prahe',category:'osobnosti_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1810,question:'Kto je súčasný slovenský prezident (2025)?',answer:'Peter Pellegrini',category:'osobnosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1901,question:'Ako sa volá najznámejšie pohorie na Slovensku?',answer:'Vysoké Tatry',category:'pohoria_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1902,question:'V ktorom pohorí sa nachádza Chopok?',answer:'Nízke Tatry',category:'pohoria_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1903,question:'Ako sa volá pohorie pri Banskej Bystrici?',answer:'Kremnické vrchy (alebo Veľká Fatra)',category:'pohoria_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1904,question:'V akom pohorí je Demänovská jaskyňa?',answer:'Nízke Tatry',category:'pohoria_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1905,question:'Aký je najvyšší vrch Malej Fatry?',answer:'Veľký Kriváň (1 709 m)',category:'pohoria_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1906,question:'V ktorom pohorí sa nachádza Ďumbier?',answer:'Nízke Tatry',category:'pohoria_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1907,question:'Aké pohorie oddeľuje Spiš od Liptova?',answer:'Nízke Tatry',category:'pohoria_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:1908,question:'V ktorom pohorí leží Štrbské pleso?',answer:'Vysoké Tatry',category:'pohoria_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:1909,question:'Aký je najvyšší vrch Nízkych Tatier?',answer:'Ďumbier (2 043 m)',category:'pohoria_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:1910,question:'V ktorom pohorí sa nachádza Martinské hole?',answer:'Veľká Fatra',category:'pohoria_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2001,question:'Čo znamená skratka PC?',answer:'Personal Computer (osobný počítač)',category:'informatika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2002,question:'Čo je internet?',answer:'Celosvetová sieť prepojených počítačov',category:'informatika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2003,question:'Čo znamená skratka URL?',answer:'Uniform Resource Locator (webová adresa)',category:'informatika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2004,question:'Čo je algoritmus?',answer:'Presný postup krokov na vyriešenie úlohy',category:'informatika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2005,question:'V akej číselnej sústave pracuje počítač?',answer:'Dvojkovej (binárnej)',category:'informatika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2006,question:'Čo je RAM?',answer:'Operačná pamäť počítača (Random Access Memory)',category:'informatika_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2007,question:'Kto je považovaný za otca informatiky?',answer:'Alan Turing',category:'informatika_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2008,question:'Čo je to pixel?',answer:'Najmenší bod na obrazovke',category:'informatika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2009,question:'Čo je USB?',answer:'Universal Serial Bus – štandard na pripájanie zariadení',category:'informatika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2010,question:'Aký programovací jazyk sa učí často ako prvý?',answer:'Python (alebo Scratch)',category:'informatika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2101,question:'Kto napísal „Marína"?',answer:'Andrej Sládkovič',category:'spisovatelia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2102,question:'Kto bol Martin Kukučín?',answer:'Slovenský spisovateľ, autor „Dom v stráni"',category:'spisovatelia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2103,question:'Kto bol Janko Kráľ?',answer:'Romantický básnik, štúrovský',category:'spisovatelia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2104,question:'Ako sa volal slovenský dramatik, autor „Kocúrkova"?',answer:'Ján Chalupka',category:'spisovatelia_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2105,question:'Ktorý slovenský autor dostal Nobelovu cenu?',answer:'Žiadny slovenský autor nezískal Nobelovu cenu',category:'spisovatelia_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2106,question:'Kto napísal rozprávku „Soľ nad zlato"?',answer:'Pavol Dobšinský (zapísal ľudovú rozprávku)',category:'spisovatelia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2107,question:'Kto bol Pavol Országh Hviezdoslav?',answer:'Najvýznamnejší slovenský básnik, autor Hájnikovej ženy',category:'spisovatelia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2108,question:'Kto napísal „Mama"?',answer:'Ján Smrek',category:'spisovatelia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2109,question:'Kto bol Dominik Tatarka?',answer:'Slovenský spisovateľ, autor „Démona súhlasu"',category:'spisovatelia_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2110,question:'Kto napísal „Zbojnícku mladosť"?',answer:'Ľudo Ondrejov',category:'spisovatelia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2201,question:'V akom športe sa Slovensko stalo majstrom sveta v roku 2002?',answer:'Hokej',category:'sport_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2202,question:'Kto je Anastasia Kuzminová?',answer:'Slovenská biatlonistka, olympijská víťazka',category:'sport_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2203,question:'V akom meste hrajú HC Slovan?',answer:'Bratislava',category:'sport_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2204,question:'Kto je Petra Vlhová?',answer:'Slovenská lyžiarka, olympijská víťazka',category:'sport_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2205,question:'V ktorom roku bolo slovenské hokejové zlato na MS?',answer:'2002 (Göteborg)',category:'sport_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2206,question:'Kto bol prvý Slovák v NHL?',answer:'Peter Šťastný',category:'sport_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2207,question:'Ako sa volá slovenský futbalový klub zo Žiliny?',answer:'MŠK Žilina',category:'sport_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2208,question:'Kto je Marek Hamšík?',answer:'Najslávnejší slovenský futbalista',category:'sport_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2209,question:'V akom športe súťažili bratia Škantar?',answer:'Vodný slalom (kanoistika)',category:'sport_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2210,question:'Koľko olympijských medailí má Slovensko celkovo (približne)?',answer:'Približne 30+',category:'sport_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2301,question:'Dokončite: „Bez práce nie sú..."',answer:'koláče',category:'prislovia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2302,question:'Dokončite: „Kto druhému jamu kope..."',answer:'sám do nej padne',category:'prislovia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2303,question:'Dokončite: „Ráno múdrejšie..."',answer:'večera',category:'prislovia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2304,question:'Dokončite: „Tichá voda..."',answer:'brehy myje',category:'prislovia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2305,question:'Dokončite: „Kto sa smeje naposledy..."',answer:'ten sa smeje najlepšie',category:'prislovia_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2306,question:'Dokončite: „Vrana k vrane..."',answer:'sadá',category:'prislovia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2307,question:'Dokončite: „Aká matka, taká..."',answer:'Katka',category:'prislovia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2308,question:'Dokončite: „Lepší vrabec v hrsti ako..."',answer:'holub na streche',category:'prislovia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2309,question:'Dokončite: „Sýty hladnému..."',answer:'neverí',category:'prislovia_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2310,question:'Dokončite: „Komu niet rady, tomu niet..."',answer:'pomoci',category:'prislovia_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2401,question:'Aké zviera je najväčší cicavec na Slovensku?',answer:'Medveď hnedý',category:'zvierata_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2402,question:'Aký vták je symbolom Tatier?',answer:'Orol skalný',category:'zvierata_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2403,question:'Aký had je jedovatý na Slovensku?',answer:'Vretenica severná',category:'zvierata_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2404,question:'Žije na Slovensku vlk?',answer:'Áno, vlk dravý žije v slovenských horách',category:'zvierata_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2405,question:'Aký vták je najmenší v Európe?',answer:'Králik zlatohlavý',category:'zvierata_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2406,question:'Koľko nôh má pavúk?',answer:'8',category:'zvierata_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2407,question:'Aká ryba žije v tatranských plesách?',answer:'Pstruh potočný (alebo lipeň)',category:'zvierata_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2408,question:'Čo je to rys ostrovid?',answer:'Veľká mačkovitá šelma žijúca v slovenských lesoch',category:'zvierata_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2409,question:'Aký je najväčší slovenský dravec (vták)?',answer:'Orol skalný',category:'zvierata_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2410,question:'Aký druh sovy je najväčší na Slovensku?',answer:'Výr skalný',category:'zvierata_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2501,question:'Ako sa volá najväčší hrad na Slovensku?',answer:'Spišský hrad',category:'hrady_zamky',difficulty:'junior',scope:'sk',type:'normal'},
{id:2502,question:'V ktorom meste sa nachádza Bratislavský hrad?',answer:'Bratislava',category:'hrady_zamky',difficulty:'junior',scope:'sk',type:'normal'},
{id:2503,question:'Ktorý hrad je známy Čachtickou paňou (Alžbetou Bátoryovou)?',answer:'Čachtický hrad',category:'hrady_zamky',difficulty:'level1',scope:'sk',type:'normal'},
{id:2504,question:'Na ktorej rieke stojí Trenčiansky hrad?',answer:'Váh',category:'hrady_zamky',difficulty:'level1',scope:'sk',type:'normal'},
{id:2505,question:'Ako sa volá zámok v Bojniciach?',answer:'Bojnický zámok',category:'hrady_zamky',difficulty:'junior',scope:'sk',type:'normal'},
{id:2506,question:'Ktorý slovenský hrad je zapísaný v UNESCO?',answer:'Spišský hrad',category:'hrady_zamky',difficulty:'level1',scope:'sk',type:'normal'},
{id:2507,question:'Na Orave sa nachádza známy hrad – aký?',answer:'Oravský hrad',category:'hrady_zamky',difficulty:'junior',scope:'sk',type:'normal'},
{id:2508,question:'Kde sa natáčal film Nosferatu (1922)?',answer:'Oravský hrad',category:'hrady_zamky',difficulty:'level2',scope:'sk',type:'normal'},
{id:2509,question:'Koľko hradov a zámkov má približne Slovensko?',answer:'Vyše 200',category:'hrady_zamky',difficulty:'level2',scope:'sk',type:'normal'},
{id:2510,question:'Ktorý hrad pri Žiari nad Hronom je jedným z najstarších?',answer:'Šášovský hrad',category:'hrady_zamky',difficulty:'level2',scope:'sk',type:'normal'},
{id:2601,question:'Aká je najdlhšia rieka Slovenska?',answer:'Váh (403 km)',category:'rieky_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2602,question:'Cez ktoré hlavné mesto tečie Dunaj?',answer:'Bratislava',category:'rieky_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2603,question:'Aká rieka tečie cez Košice?',answer:'Hornád',category:'rieky_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2604,question:'Do akej rieky sa vlieva Váh?',answer:'Dunaj',category:'rieky_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2605,question:'Aká rieka tvorí časť hranice s Poľskom?',answer:'Dunajec',category:'rieky_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2606,question:'V akom meste sa Orava vlieva do Váhu?',answer:'Kraľovany',category:'rieky_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2607,question:'Aká rieka preteká Banskou Bystricou?',answer:'Hron',category:'rieky_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2608,question:'Kde pramení Váh?',answer:'Pod Kráľovou hoľou – sútok Čierneho a Bieleho Váhu',category:'rieky_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2609,question:'Aká rieka tečie cez Žilinu?',answer:'Váh',category:'rieky_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2610,question:'Do akého mora sa vlieva Dunaj?',answer:'Čierne more',category:'rieky_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2701,question:'Aké farby má slovenská vlajka?',answer:'Biela, modrá, červená (zhora nadol)',category:'vlajky_erby_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2702,question:'Čo je na slovenskom štátnom znaku?',answer:'Dvojitý kríž na trojvrší',category:'vlajky_erby_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2703,question:'Aký symbol má na erbe mesto Košice?',answer:'Anjel s erbom (kríž a lilie)',category:'vlajky_erby_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2704,question:'Aké trojvršie je na slovenskom znaku?',answer:'Tri vrchy – Tatru, Matru a Fatru',category:'vlajky_erby_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2705,question:'Aká farba pozadia je na slovenskom znaku?',answer:'Červená',category:'vlajky_erby_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2706,question:'Kedy bola prijatá súčasná slovenská vlajka?',answer:'1992 (pred vznikom SR)',category:'vlajky_erby_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2707,question:'Aký erb má hlavné mesto Bratislava?',answer:'Hradba s tromi vežami a bránou',category:'vlajky_erby_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2708,question:'Čo symbolizuje dvojitý kríž na slovenskom znaku?',answer:'Kresťanskú tradíciu (cyrilometodskú)',category:'vlajky_erby_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2801,question:'Píše sa „kedy" alebo „kedí"?',answer:'kedy',category:'pravopis_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2802,question:'Píše sa „výborný" s „y" alebo „i"?',answer:'S „ý" – výborný',category:'pravopis_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2803,question:'Je „ryba" vybrané slovo?',answer:'Áno',category:'pravopis_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2804,question:'Píše sa „my" alebo „mi" v „my sme deti"?',answer:'My (zámeno)',category:'pravopis_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2805,question:'Aké vybrané slová začínajú na „b"?',answer:'byť, bývať, býk, Bystrica, bylina, bystrý, bydlo, kobyla, obyčaj…',category:'pravopis_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2806,question:'Píše sa „síce" alebo „síce"?',answer:'síce (s dlhým í)',category:'pravopis_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2807,question:'Koľko je skupín vybraných slov v slovenčine?',answer:'7 skupín (po b, m, p, r, s, v, z)',category:'pravopis_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2808,question:'Aký je rozdiel medzi „pýtať" a „pitať"?',answer:'Pýtať (vybrané slovo po p) = opytovať sa',category:'pravopis_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2809,question:'Kde je chyba: „Prídem v pondielok."?',answer:'Žiadna chyba – veta je správna',category:'pravopis_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2810,question:'Píše sa „dcéra" s mäkčeňom nad c?',answer:'Nie – píše sa dcéra bez mäkčeňa',category:'pravopis_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2901,question:'Kto bol Aurel Stodola?',answer:'Slovenský vynálezca, priekopník turbín a protéz',category:'veda_technika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2902,question:'Čo vynašiel Jozef Murgaš?',answer:'Priekopník bezdrôtového prenosu správ',category:'veda_technika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2903,question:'Kto bol Štefan Banič?',answer:'Vynálezca padáku',category:'veda_technika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2904,question:'Čo vynašiel Štefan Banič?',answer:'Padák',category:'veda_technika_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:2905,question:'Aká slovenská firma vyrába lietajúce auto?',answer:'AeroMobil',category:'veda_technika_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2906,question:'V ktorom roku vyletela prvá slovenská družica do vesmíru?',answer:'2017 (skCUBE)',category:'veda_technika_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:2907,question:'Čo je atómová elektráreň Mochovce?',answer:'Jadrová elektráreň pri Leviciach',category:'veda_technika_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:2908,question:'Kto bol Ján Bahýľ?',answer:'Vynálezca, skonštruoval vrtuľník (1905)',category:'veda_technika_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3001,question:'Aké je najrozšírenejšie náboženstvo na Slovensku?',answer:'Kresťanstvo (rímskokatolícke)',category:'nabozenstvo_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3002,question:'Kto sú patróni Slovenska?',answer:'Sv. Cyril a Metod',category:'nabozenstvo_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3003,question:'Kde je najväčšie pútne miesto na Slovensku?',answer:'Levoča (Mariánska hora)',category:'nabozenstvo_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3004,question:'Kto bol Majster Pavol z Levoče?',answer:'Stredoveký rezbár, autor najvyššieho dreveného oltára na svete',category:'nabozenstvo_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3005,question:'Kedy slávia kresťania Vianoce?',answer:'25. decembra',category:'nabozenstvo_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3006,question:'Aký kostol je Dóm sv. Alžbety?',answer:'Gotický kostol v Košiciach, najväčší na Slovensku',category:'nabozenstvo_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3007,question:'Koľko percent Slovákov sa hlási ku kresťanstvu (približne)?',answer:'Približne 60-70 %',category:'nabozenstvo_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3008,question:'Kto bol Gorazd?',answer:'Žiak Cyrila a Metoda, prvý známy slovenský vzdelanec',category:'nabozenstvo_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3101,question:'Ako sa volá najstaršie divadlo na Slovensku?',answer:'Slovenské národné divadlo (SND)',category:'divadlo_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3102,question:'V ktorom meste je SND?',answer:'Bratislava',category:'divadlo_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3103,question:'Kto režíroval film „Perinbaba"?',answer:'Juraj Jakubisko',category:'divadlo_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3104,question:'Aký slovenský film zobrazuje Jánošíka?',answer:'Jánošík (1935, 2009 a ďalšie verzie)',category:'divadlo_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3105,question:'Kto boli Lasica a Satinský?',answer:'Legendárna slovenská komická dvojica',category:'divadlo_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3106,question:'Aký film nakrútil Juraj Jakubisko v roku 2008?',answer:'Bathory',category:'divadlo_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3107,question:'Kto je režisér slovenského filmu „Všetko alebo nič"?',answer:'Marta Ferencová',category:'divadlo_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3108,question:'Kde sa koná filmový festival Art Film Fest?',answer:'Košice',category:'divadlo_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3201,question:'Aké ročné obdobie je na Slovensku najchladnejšie?',answer:'Zima',category:'pocasie_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3202,question:'Koľko ročných období máme?',answer:'4 (jar, leto, jeseň, zima)',category:'pocasie_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3203,question:'Aká je priemerná teplota na Slovensku v lete?',answer:'Približne 20-25 °C',category:'pocasie_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3204,question:'Kde na Slovensku napadne najviac snehu?',answer:'Vo Vysokých Tatrách (Lomnický štít)',category:'pocasie_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3205,question:'Aký je rozdiel medzi počasím a klímou?',answer:'Počasie je aktuálny stav, klíma je dlhodobý priemer',category:'pocasie_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3206,question:'Čo je to inverzia?',answer:'Jav keď je v údoliach chladnejšie ako na horách',category:'pocasie_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3207,question:'Kedy začína astronomické leto?',answer:'21. júna (letný slnovrat)',category:'pocasie_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3208,question:'Aká je najnižšia nameraná teplota na Slovensku?',answer:'−41 °C (Vígľaš-Pstruša, 1929)',category:'pocasie_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3301,question:'Kto založil skauting?',answer:'Robert Baden-Powell (1907)',category:'skauting_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3302,question:'Aký je skautský pozdrav?',answer:'Tri zdvihnuté prsty (sľub, zákon, pomoc)',category:'skauting_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3303,question:'Čo znamená skautský zákon?',answer:'Pravidlá správania sa skauta (čestnosť, pomoc druhým...)',category:'skauting_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3304,question:'Aký je skautský symbol?',answer:'Ľalia (fleur-de-lis)',category:'skauting_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3305,question:'Kedy sa obnovil skauting na Slovensku po komunizme?',answer:'1989/1990',category:'skauting_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3306,question:'Čo je to jamboree?',answer:'Celosvetové skautské stretnutie',category:'skauting_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3307,question:'Aké je skautské heslo?',answer:'Buď pripravený!',category:'skauting_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3308,question:'Aký uzol je základný skautský uzol?',answer:'Lodný uzol (plochý uzol)',category:'skauting_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3401,question:'Aká je najstaršia banská šachta na Slovensku?',answer:'V Banskej Štiavnici',category:'zaujimavosti_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3402,question:'V ktorom slovenskom meste je UNESCO jaskyňa?',answer:'Ochtinská aragonitová jaskyňa',category:'zaujimavosti_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3403,question:'Koľko lokalít UNESCO má Slovensko (približne)?',answer:'7 (kultúrnych a prírodných)',category:'zaujimavosti_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3404,question:'Aký gejzír sa nachádza na Slovensku?',answer:'Herľanský gejzír',category:'zaujimavosti_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:3405,question:'Kde na Slovensku je drevený betlehem?',answer:'V Rajeckej Lesnej (Slovenský betlehem)',category:'zaujimavosti_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3406,question:'Aký vynález pochádza zo Slovenska?',answer:'Padák (Štefan Banič)',category:'zaujimavosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3407,question:'Aká je najdlhšia jaskyňa na Slovensku?',answer:'Demänovský jaskynný systém',category:'zaujimavosti_sk',difficulty:'level1',scope:'sk',type:'normal'},
{id:3408,question:'Koľko obyvateľov má Slovensko (približne)?',answer:'Približne 5,4 milióna',category:'zaujimavosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3409,question:'Aké auto sa vyrába v Bratislave?',answer:'Volkswagen (závod v Devínskej Novej Vsi)',category:'zaujimavosti_sk',difficulty:'junior',scope:'sk',type:'normal'},
{id:3410,question:'Ktoré slovenské mesto sa volá „perla Šariša"?',answer:'Prešov',category:'zaujimavosti_sk',difficulty:'level2',scope:'sk',type:'normal'},
{id:5001,question:'Kto objavil Ameriku v roku 1492?',answer:'Krištof Kolumbus',category:'dejiny_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5002,question:'V ktorom roku padol Berlínsky múr?',answer:'1989',category:'dejiny_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5003,question:'Kto bol prvý človek na Mesiaci?',answer:'Neil Armstrong (1969)',category:'dejiny_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5004,question:'V ktorom roku začala 2. svetová vojna?',answer:'1939',category:'dejiny_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5005,question:'Kto bol Napoleon Bonaparte?',answer:'Francúzsky cisár a vojenský vodca',category:'dejiny_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5006,question:'V akom roku bola Francúzska revolúcia?',answer:'1789',category:'dejiny_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5007,question:'Kto napísal Deklaráciu nezávislosti USA?',answer:'Thomas Jefferson',category:'dejiny_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5008,question:'Aká civilizácia postavila pyramídy v Gíze?',answer:'Staroveký Egypt',category:'dejiny_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5009,question:'Kto bol Džingischán?',answer:'Zakladateľ Mongolskej ríše',category:'dejiny_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5010,question:'V ktorom roku skončila 1. svetová vojna?',answer:'1918',category:'dejiny_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5011,question:'Čo bola studená vojna?',answer:'Politický konflikt medzi USA a ZSSR (1947-1991)',category:'dejiny_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5012,question:'Kto bol Martin Luther King?',answer:'Americký bojovník za občianske práva',category:'dejiny_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5101,question:'Aký je najväčší oceán?',answer:'Tichý oceán',category:'geografia_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5102,question:'Aký kontinent je najväčší?',answer:'Ázia',category:'geografia_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5103,question:'Aká je najdlhšia rieka na svete?',answer:'Níl (alebo Amazonka)',category:'geografia_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5104,question:'Aký je najvyšší vrch na svete?',answer:'Mount Everest (8 849 m)',category:'geografia_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5105,question:'Koľko kontinentov má Zem?',answer:'7',category:'geografia_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5106,question:'Aká je najväčšia púšť na svete?',answer:'Sahara (horúca) alebo Antarktída (celkovo)',category:'geografia_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5107,question:'V akej krajine sa nachádza Veľký korálový útes?',answer:'Austrália',category:'geografia_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5108,question:'Aký prieplav spája Atlantický a Tichý oceán?',answer:'Panamský prieplav',category:'geografia_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5109,question:'Aký je najhlbší bod oceánu?',answer:'Mariánsky priekop (11 034 m)',category:'geografia_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5110,question:'Aký je najväčší ostrov na svete?',answer:'Grónsko',category:'geografia_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5111,question:'V akej krajine sa nachádza Amazonský prales?',answer:'Brazília (a ďalšie krajiny)',category:'geografia_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5112,question:'Aké jazero je najväčšie na svete?',answer:'Kaspické more (jazero)',category:'geografia_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5201,question:'Aké je hlavné mesto Francúzska?',answer:'Paríž',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5202,question:'Aké je hlavné mesto Japonska?',answer:'Tokio',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5203,question:'Aké je hlavné mesto USA?',answer:'Washington, D.C.',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5204,question:'Aké je hlavné mesto Nemecka?',answer:'Berlín',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5205,question:'Aké je hlavné mesto Talianska?',answer:'Rím',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5206,question:'Aké je hlavné mesto Austrálie?',answer:'Canberra',category:'hlavne_mesta',difficulty:'level1',scope:'svet',type:'normal'},
{id:5207,question:'Aké je hlavné mesto Brazílie?',answer:'Brasília',category:'hlavne_mesta',difficulty:'level1',scope:'svet',type:'normal'},
{id:5208,question:'Aké je hlavné mesto Kanady?',answer:'Ottawa',category:'hlavne_mesta',difficulty:'level1',scope:'svet',type:'normal'},
{id:5209,question:'Aké je hlavné mesto Turecka?',answer:'Ankara',category:'hlavne_mesta',difficulty:'level1',scope:'svet',type:'normal'},
{id:5210,question:'Aké je hlavné mesto Mjanmarska?',answer:'Nepjido',category:'hlavne_mesta',difficulty:'level2',scope:'svet',type:'normal'},
{id:5211,question:'Aké je hlavné mesto Švajčiarska?',answer:'Bern',category:'hlavne_mesta',difficulty:'level1',scope:'svet',type:'normal'},
{id:5212,question:'Aké je hlavné mesto Nového Zélandu?',answer:'Wellington',category:'hlavne_mesta',difficulty:'level2',scope:'svet',type:'normal'},
{id:5213,question:'Aké je hlavné mesto Egypta?',answer:'Káhira',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5214,question:'Aké je hlavné mesto Španielska?',answer:'Madrid',category:'hlavne_mesta',difficulty:'junior',scope:'svet',type:'normal'},
{id:5301,question:'V akom športe sa používa žltá loptička?',answer:'Tenis',category:'sport_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5302,question:'Koľko hráčov má futbalový tím na ihrisku?',answer:'11',category:'sport_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5303,question:'Kto je Lionel Messi?',answer:'Argentínsky futbalista, považovaný za najlepšieho hráča',category:'sport_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5304,question:'Kde sa konali prvé moderné olympijské hry?',answer:'Atény, 1896',category:'sport_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5305,question:'Koľko hráčov je v basketbalovom tíme na ihrisku?',answer:'5',category:'sport_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5306,question:'Čo je to Tour de France?',answer:'Najslávnejšie cyklistické preteky na svete',category:'sport_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5307,question:'V akej krajine vznikol futbal?',answer:'Anglicko',category:'sport_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5308,question:'Kto je Usain Bolt?',answer:'Jamajský atlét, najrýchlejší človek v histórii',category:'sport_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5309,question:'V akom športe sa používa termín „smečovať"?',answer:'Volejbal (alebo tenis)',category:'sport_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5310,question:'Kto je Michael Jordan?',answer:'Americký basketbalista, legenda NBA',category:'sport_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5311,question:'Koľko setov sa hrá maximálne v tenise (Grand Slam muži)?',answer:'5',category:'sport_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5312,question:'Kto drží rekord v počte titulov F1?',answer:'Lewis Hamilton / Michael Schumacher (7)',category:'sport_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5401,question:'Kto skomponoval operu „Čarovná flauta"?',answer:'Wolfgang Amadeus Mozart',category:'opera_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5402,question:'V akej krajine vznikla opera?',answer:'Taliansko',category:'opera_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5403,question:'Kto napísal operu „Carmen"?',answer:'Georges Bizet',category:'opera_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5404,question:'Čo je to libreto?',answer:'Text (dejový podklad) opery',category:'opera_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5405,question:'Kto skomponoval operu „Aida"?',answer:'Giuseppe Verdi',category:'opera_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5406,question:'Aký druh hlasu je soprán?',answer:'Najvyšší ženský hlas',category:'opera_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5407,question:'Kde sa nachádza slávna opera „La Scala"?',answer:'Miláno, Taliansko',category:'opera_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5408,question:'Kto skomponoval „Labutie jazero"?',answer:'Piotr Iľjič Čajkovskij',category:'opera_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5501,question:'Kto napísal „Rómea a Júliu"?',answer:'William Shakespeare',category:'divadlo_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5502,question:'V akej krajine sa nachádza divadlo Globe?',answer:'Anglicko (Londýn)',category:'divadlo_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5503,question:'Kto napísal „Hamleta"?',answer:'William Shakespeare',category:'divadlo_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5504,question:'Čo je to muzikál?',answer:'Divadelné predstavenie s hudbou, spevom a tancom',category:'divadlo_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5505,question:'Ako sa volá najslávnejší muzikál o opernom prízraku?',answer:'Fantóm opery (Phantom of the Opera)',category:'divadlo_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5506,question:'Kde sa nachádza Broadway?',answer:'New York, USA',category:'divadlo_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5507,question:'Kto bol Molière?',answer:'Francúzsky dramatik a herec (komédie)',category:'divadlo_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5508,question:'Aký antický dramatik napísal „Kráľa Oidipa"?',answer:'Sofokles',category:'divadlo_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5601,question:'Akú farbu má japonská vlajka?',answer:'Biela s červeným kruhom',category:'vlajky_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5602,question:'Aké farby má francúzska vlajka?',answer:'Modrá, biela, červená (trikolóra)',category:'vlajky_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5603,question:'Aká krajina má na vlajke javorový list?',answer:'Kanada',category:'vlajky_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5604,question:'Ktorá krajina má na vlajke hviezdy v kruhu?',answer:'Európska únia (vlajka)',category:'vlajky_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5605,question:'Aká krajina má zelenú vlajku s bielym polmesiacom?',answer:'Pakistan',category:'vlajky_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5606,question:'Koľko pruhov má americká vlajka?',answer:'13',category:'vlajky_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5607,question:'Aká krajina má na vlajke Union Jack?',answer:'Spojené kráľovstvo (Veľká Británia)',category:'vlajky_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5608,question:'Ktorá škandinávska krajina má modrú vlajku so žltým krížom?',answer:'Švédsko',category:'vlajky_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5609,question:'Aká krajina má vlajku s drakom?',answer:'Wales (alebo Bhután)',category:'vlajky_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5610,question:'Koľko hviezd má vlajka EÚ?',answer:'12',category:'vlajky_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5611,question:'Aká krajina má na vlajke cedrus?',answer:'Libanon',category:'vlajky_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5612,question:'Aké farby má nemecká vlajka?',answer:'Čierna, červená, zlatá',category:'vlajky_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5701,question:'Kto namaľoval „Monu Lízu"?',answer:'Leonardo da Vinci',category:'umenie_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5702,question:'V akom múzeu je Mona Líza?',answer:'Louvre (Paríž)',category:'umenie_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5703,question:'Kto namaľoval strop Sixtínskej kaplnky?',answer:'Michelangelo',category:'umenie_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5704,question:'Kto namaľoval „Hviezdnu noc"?',answer:'Vincent van Gogh',category:'umenie_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5705,question:'Čo je to impresionizmus?',answer:'Umelecký smer zachytávajúci okamžitý dojem svetla a farby',category:'umenie_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5706,question:'Kto namaľoval „Výkrik"?',answer:'Edvard Munch',category:'umenie_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5707,question:'Kto bol Pablo Picasso?',answer:'Španielsky maliar, zakladateľ kubizmu',category:'umenie_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5708,question:'Čo je to renesancia?',answer:'Kultúrne obdobie (14.-17. stor.) znovuzrodenia antiky',category:'umenie_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5709,question:'Kto vytvoril sochu Dávida?',answer:'Michelangelo',category:'umenie_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5710,question:'Aký smer reprezentuje Salvador Dalí?',answer:'Surrealizmus',category:'umenie_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5801,question:'Kto vynašiel žiarovku?',answer:'Thomas Edison',category:'veda_technika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5802,question:'Čo objavil Isaac Newton?',answer:'Zákon gravitácie',category:'veda_technika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5803,question:'Kto bol Albert Einstein?',answer:'Fyzik, autor teórie relativity',category:'veda_technika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5804,question:'Aký prvok má chemickú značku O?',answer:'Kyslík (Oxygen)',category:'veda_technika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5805,question:'Koľko planét má slnečná sústava?',answer:'8',category:'veda_technika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5806,question:'Kto vynašiel telefón?',answer:'Alexander Graham Bell',category:'veda_technika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5807,question:'Aká je chemická značka vody?',answer:'H₂O',category:'veda_technika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5808,question:'Kto objavil penicilin?',answer:'Alexander Fleming',category:'veda_technika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5809,question:'Aká je rýchlosť svetla (približne)?',answer:'Približne 300 000 km/s',category:'veda_technika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5810,question:'Čo je DNA?',answer:'Kyselina deoxyribonukleová – nositeľ genetickej informácie',category:'veda_technika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5811,question:'Kto je Nikola Tesla?',answer:'Vynálezca, priekopník striedavého prúdu',category:'veda_technika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5812,question:'Kto bol Galileo Galilei?',answer:'Taliansky astronóm a fyzik, otec modernej vedy',category:'veda_technika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5901,question:'Kto napísal „Harryho Pottera"?',answer:'J. K. Rowlingová',category:'literatura_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5902,question:'Kto napísal „Malého princa"?',answer:'Antoine de Saint-Exupéry',category:'literatura_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5903,question:'Kto napísal „Dona Quijota"?',answer:'Miguel de Cervantes',category:'literatura_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5904,question:'Kto napísal „Vojnu a mier"?',answer:'Lev Nikolajevič Tolstoj',category:'literatura_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5905,question:'Kto napísal „1984"?',answer:'George Orwell',category:'literatura_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5906,question:'Kto napísal „Odysseu"?',answer:'Homér',category:'literatura_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5907,question:'Kto napísal „Starec a more"?',answer:'Ernest Hemingway',category:'literatura_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:5908,question:'Kto napísal „Hobita"?',answer:'J. R. R. Tolkien',category:'literatura_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:5909,question:'Kto napísal „Rozprávky z tisíc a jednej noci"?',answer:'Zbierka arabských rozprávok (anonym)',category:'literatura_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:5910,question:'Kto napísal „Zločin a trest"?',answer:'Fiodor Dostojevskij',category:'literatura_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6001,question:'Kto skomponoval „Pre Elišku" (Für Elise)?',answer:'Ludwig van Beethoven',category:'hudba_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6002,question:'Aká skupina spievala „Let It Be"?',answer:'The Beatles',category:'hudba_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6003,question:'Kto bol „kráľ popu"?',answer:'Michael Jackson',category:'hudba_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6004,question:'Koľko riadkov má notová osnova?',answer:'5',category:'hudba_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6005,question:'Kto skomponoval „Deviatu symfóniu" s „Ódou na radosť"?',answer:'Ludwig van Beethoven',category:'hudba_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6006,question:'Akú hudobnú skupinu založil Freddie Mercury?',answer:'Queen',category:'hudba_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6007,question:'Čo je to koncert pre sólový nástroj?',answer:'Skladba pre sólový nástroj s orchestrom',category:'hudba_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6008,question:'Kto skomponoval „Štyri ročné obdobia"?',answer:'Antonio Vivaldi',category:'hudba_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6009,question:'Aký hudobný nástroj má 88 kláves?',answer:'Klavír',category:'hudba_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6010,question:'Kto bol Johann Sebastian Bach?',answer:'Nemecký skladateľ, majster barokovej hudby',category:'hudba_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6011,question:'Kto skomponoval operu „Don Giovanni"?',answer:'Wolfgang Amadeus Mozart',category:'hudba_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6101,question:'Aký film zobrazuje potopenie slávnej lode?',answer:'Titanic',category:'film_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6102,question:'Kto režíroval „Hviezdne vojny" (Star Wars)?',answer:'George Lucas',category:'film_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6103,question:'Ako sa volá animovaná ryba hľadajúca syna?',answer:'Hľadá sa Nemo',category:'film_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6104,question:'Kto hrá Iron Mana v Marvel filmoch?',answer:'Robert Downey Jr.',category:'film_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6105,question:'Kto režíroval „Jurský park"?',answer:'Steven Spielberg',category:'film_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6106,question:'V ktorom roku mal premiéru prvý zvukový film?',answer:'1927 (Jazzový spevák)',category:'film_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6107,question:'Aký režisér natočil „Krstného otca"?',answer:'Francis Ford Coppola',category:'film_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6108,question:'Ako sa volá cena americkej filmovej akadémie?',answer:'Oscar',category:'film_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6109,question:'Kto je režisér filmov „Temný rytier" a „Inception"?',answer:'Christopher Nolan',category:'film_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6110,question:'Kto hrá Jamesa Bonda v posledných filmoch (do 2021)?',answer:'Daniel Craig',category:'film_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6201,question:'Koľko je π (pí) na dve desatinné miesta?',answer:'3,14',category:'matematika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6202,question:'Koľko je 2 na piatu?',answer:'32',category:'matematika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6203,question:'Čo je prvočíslo?',answer:'Číslo deliteľné len 1 a sebou samým',category:'matematika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6204,question:'Koľko uhlov má trojuholník?',answer:'3 (súčet 180°)',category:'matematika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6205,question:'Aký je objem kocky s hranou 3 cm?',answer:'27 cm³',category:'matematika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6206,question:'Koľko je faktoriál 5 (5!)?',answer:'120',category:'matematika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6207,question:'Čo je to Fibonacciho postupnosť?',answer:'Postupnosť kde každé číslo je súčtom dvoch predchádzajúcich: 1,1,2,3,5,8...',category:'matematika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6208,question:'Aká je hodnota odmocniny z 2 (približne)?',answer:'Približne 1,414',category:'matematika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6209,question:'Koľko stupňov je v kruhu?',answer:'360°',category:'matematika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6210,question:'Aký je vzorec na obsah trojuholníka?',answer:'S = (a × v) / 2',category:'matematika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6301,question:'Kto bol Mahátma Gándhí?',answer:'Indický vodca, bojovník za nezávislosť nenásilnou cestou',category:'osobnosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6302,question:'Kto je Elon Musk?',answer:'Podnikateľ, zakladateľ SpaceX a Tesla',category:'osobnosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6303,question:'Kto bola Matka Tereza?',answer:'Rehoľná sestra, nositeľka Nobelovej ceny za mier',category:'osobnosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6304,question:'Kto bol Nelson Mandela?',answer:'Juhoafrický prezident, bojovník proti apartheidu',category:'osobnosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6305,question:'Kto je Steve Jobs?',answer:'Spoluzakladateľ Apple',category:'osobnosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6306,question:'Kto bola Kleopatra?',answer:'Posledná faraónka starovekého Egypta',category:'osobnosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6307,question:'Kto bol Leonardo da Vinci?',answer:'Taliansky génius – maliar, vynálezca, vedec',category:'osobnosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6308,question:'Kto bola Marie Curie?',answer:'Vedkyňa, objavila rádium, 2× Nobelova cena',category:'osobnosti_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6309,question:'Kto bol Abraham Lincoln?',answer:'Americký prezident, zrušil otroctvo',category:'osobnosti_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6310,question:'Kto je Bill Gates?',answer:'Spoluzakladateľ Microsoftu',category:'osobnosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6401,question:'Aký je najväčší cicavec na svete?',answer:'Plejtvákovitá veľryba (vráskavec)',category:'priroda_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6402,question:'Aký je najrýchlejší pozemný živočích?',answer:'Gepard',category:'priroda_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6403,question:'Koľko nôh má stonožka?',answer:'Rôzny počet, nie presne 100 (30-354)',category:'priroda_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6404,question:'Aký je najväčší dažďový prales na svete?',answer:'Amazonský dažďový prales',category:'priroda_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6405,question:'Aký je najvyšší strom na svete?',answer:'Sekvoja vždyzelená (Hyperion)',category:'priroda_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6406,question:'Čo je to koralový útes?',answer:'Podmorská štruktúra vytvorená koralmi',category:'priroda_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6407,question:'Aký je najstarší strom na svete?',answer:'Borovica dlhoveká (Methuselah, cca 4 850 rokov)',category:'priroda_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6408,question:'Aký je najväčší vták na svete?',answer:'Pštros africký',category:'priroda_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6409,question:'Aký je najmenší vták na svete?',answer:'Kolibríček kubánsky',category:'priroda_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6410,question:'Aké zviera je najpomalšie na svete?',answer:'Leňochod',category:'priroda_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6501,question:'Kto založil Facebook (Meta)?',answer:'Mark Zuckerberg',category:'informatika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6502,question:'Čo znamená WWW?',answer:'World Wide Web',category:'informatika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6503,question:'V akom roku bol vyrobený prvý iPhone?',answer:'2007',category:'informatika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6504,question:'Čo je to operačný systém?',answer:'Základný softvér riadiaci počítač (Windows, macOS, Linux)',category:'informatika_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6505,question:'Kto vytvoril Linux?',answer:'Linus Torvalds',category:'informatika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6506,question:'Čo je to AI (umelá inteligencia)?',answer:'Technológia napodobňujúca ľudské myslenie',category:'informatika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6507,question:'Čo je to blockchain?',answer:'Distribuovaná databáza/reťazec blokov (základ kryptomien)',category:'informatika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6508,question:'Kto je zakladateľ Amazonu?',answer:'Jeff Bezos',category:'informatika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6509,question:'Čo znamená HTML?',answer:'HyperText Markup Language',category:'informatika_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6510,question:'Kto vynašiel World Wide Web?',answer:'Tim Berners-Lee',category:'informatika_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6601,question:'Aká je najbližšia hviezda k Zemi?',answer:'Slnko',category:'astronomia',difficulty:'junior',scope:'svet',type:'normal'},
{id:6602,question:'Koľko planét má slnečná sústava?',answer:'8',category:'astronomia',difficulty:'junior',scope:'svet',type:'normal'},
{id:6603,question:'Aká planéta je najväčšia v slnečnej sústave?',answer:'Jupiter',category:'astronomia',difficulty:'junior',scope:'svet',type:'normal'},
{id:6604,question:'Čo je to Mliečna dráha?',answer:'Naša galaxia',category:'astronomia',difficulty:'junior',scope:'svet',type:'normal'},
{id:6605,question:'Ako dlho trvá jeden obeh Zeme okolo Slnka?',answer:'Približne 365 dní',category:'astronomia',difficulty:'junior',scope:'svet',type:'normal'},
{id:6606,question:'Aká planéta je známa pre svoje prstence?',answer:'Saturn',category:'astronomia',difficulty:'junior',scope:'svet',type:'normal'},
{id:6607,question:'Čo je to čierna diera?',answer:'Objekt s tak silnou gravitáciou, že z neho neunikne ani svetlo',category:'astronomia',difficulty:'level1',scope:'svet',type:'normal'},
{id:6608,question:'Aká je teplota na povrchu Slnka?',answer:'Približne 5 500 °C',category:'astronomia',difficulty:'level1',scope:'svet',type:'normal'},
{id:6609,question:'Čo je to svetelný rok?',answer:'Vzdialenosť, ktorú svetlo prejde za jeden rok',category:'astronomia',difficulty:'level1',scope:'svet',type:'normal'},
{id:6610,question:'Kedy bolo prvé pristátie na Mesiaci?',answer:'20. júla 1969',category:'astronomia',difficulty:'level1',scope:'svet',type:'normal'},
{id:6611,question:'Aká planéta je najbližšia k Slnku?',answer:'Merkúr',category:'astronomia',difficulty:'level1',scope:'svet',type:'normal'},
{id:6612,question:'Koľko mesiacov má Jupiter (približne)?',answer:'95 (známych)',category:'astronomia',difficulty:'level2',scope:'svet',type:'normal'},
{id:6701,question:'Aký je najvyšší vodopád na svete?',answer:'Angel (Salto Ángel) vo Venezuele',category:'zaujimavosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6702,question:'Koľko ľudí žije na Zemi (približne)?',answer:'Približne 8 miliárd',category:'zaujimavosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6703,question:'Aká je najmenšia krajina na svete?',answer:'Vatikán',category:'zaujimavosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6704,question:'Aká stavba je viditeľná z vesmíru? (mýtus)',answer:'Žiadna voľným okom – mýtus o Čínskom múre',category:'zaujimavosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6705,question:'Aký je najdlhší most na svete?',answer:'Danyang-Kunshan Grand Bridge (Čína, 164 km)',category:'zaujimavosti_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6706,question:'Aká je najväčšia krajina na svete?',answer:'Rusko',category:'zaujimavosti_svet',difficulty:'junior',scope:'svet',type:'normal'},
{id:6707,question:'Koľko jazykov sa hovorí na svete (približne)?',answer:'Približne 7 000',category:'zaujimavosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6708,question:'Aký je najstarší stále obývaný mesto?',answer:'Damask (Sýria)',category:'zaujimavosti_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6709,question:'Aký je najväčší diamant sveta?',answer:'Cullinan',category:'zaujimavosti_svet',difficulty:'level2',scope:'svet',type:'normal'},
{id:6710,question:'Koľko krajín je v OSN?',answer:'193',category:'zaujimavosti_svet',difficulty:'level1',scope:'svet',type:'normal'},
{id:6801,question:'Kde sa konali prvé moderné olympijské hry?',answer:'Atény, 1896',category:'olympijske_hry',difficulty:'junior',scope:'svet',type:'normal'},
{id:6802,question:'Koľko kruhov má olympijský symbol?',answer:'5',category:'olympijske_hry',difficulty:'junior',scope:'svet',type:'normal'},
{id:6803,question:'Aké farby majú olympijské kruhy?',answer:'Modrá, žltá, čierna, zelená, červená',category:'olympijske_hry',difficulty:'junior',scope:'svet',type:'normal'},
{id:6804,question:'Koľko rokov je medzi letnými olympijskými hrami?',answer:'4 roky',category:'olympijske_hry',difficulty:'junior',scope:'svet',type:'normal'},
{id:6805,question:'Kde sa konali letné OH v roku 2024?',answer:'Paríž',category:'olympijske_hry',difficulty:'junior',scope:'svet',type:'normal'},
{id:6806,question:'Kto má najviac olympijských medailí v histórii?',answer:'Michael Phelps (28 medailí)',category:'olympijske_hry',difficulty:'level1',scope:'svet',type:'normal'},
{id:6807,question:'Čo symbolizuje olympijský oheň?',answer:'Prepojenie antickej a modernej olympiády, mier',category:'olympijske_hry',difficulty:'level1',scope:'svet',type:'normal'},
{id:6808,question:'V akom meste sa konali OH v roku 2020 (2021)?',answer:'Tokio',category:'olympijske_hry',difficulty:'level1',scope:'svet',type:'normal'},
{id:6809,question:'Aký šport bol pridaný na OH 2020?',answer:'Surfing, skateboarding, lezenie',category:'olympijske_hry',difficulty:'level2',scope:'svet',type:'normal'},
{id:6810,question:'Kde sa budú konať OH v roku 2028?',answer:'Los Angeles',category:'olympijske_hry',difficulty:'level1',scope:'svet',type:'normal'},
{id:6901,question:'Z akej krajiny pochádza pizza?',answer:'Taliansko',category:'kulinarka',difficulty:'junior',scope:'svet',type:'normal'},
{id:6902,question:'Z akej krajiny pochádza sushi?',answer:'Japonsko',category:'kulinarka',difficulty:'junior',scope:'svet',type:'normal'},
{id:6903,question:'Aké jedlo je typické pre Mexiko?',answer:'Tacos (alebo burrito)',category:'kulinarka',difficulty:'junior',scope:'svet',type:'normal'},
{id:6904,question:'Z akej krajiny pochádza croissant?',answer:'Francúzsko (pôvodne Rakúsko)',category:'kulinarka',difficulty:'level1',scope:'svet',type:'normal'},
{id:6905,question:'Čo je to curry?',answer:'Korenistá zmes korení typická pre indickú kuchyňu',category:'kulinarka',difficulty:'level1',scope:'svet',type:'normal'},
{id:6906,question:'Aká krajina je známa výrobou čokolády?',answer:'Švajčiarsko (alebo Belgicko)',category:'kulinarka',difficulty:'junior',scope:'svet',type:'normal'},
{id:6907,question:'Čo je to paella?',answer:'Španielske ryžové jedlo',category:'kulinarka',difficulty:'level1',scope:'svet',type:'normal'},
{id:6908,question:'Z akej krajiny pochádza kebab?',answer:'Turecko',category:'kulinarka',difficulty:'level1',scope:'svet',type:'normal'},
{id:6909,question:'Čo je to dim sum?',answer:'Čínske malé jedlá podávané v košíkoch',category:'kulinarka',difficulty:'level2',scope:'svet',type:'normal'},
{id:6910,question:'Aké je tradičné jedlo Veľkej Británie?',answer:'Fish and chips',category:'kulinarka',difficulty:'level1',scope:'svet',type:'normal'},
{id:9001,question:'Koľko kostí má dospelý ľudský skelet?',answer:'206',category:'zaujimavosti_sk',difficulty:'junior',scope:'sk',type:'tiebreaker'},
{id:9002,question:'V ktorom roku sa Slovensko stalo členom EÚ?',answer:'2004',category:'dejiny_sk',difficulty:'junior',scope:'sk',type:'tiebreaker'},
{id:9003,question:'Aká je najväčšia planéta slnečnej sústavy?',answer:'Jupiter',category:'astronomia',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9004,question:'Koľko zubov má dospelý človek?',answer:'32',category:'zaujimavosti_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9005,question:'Aká je chemická značka zlata?',answer:'Au',category:'veda_technika_svet',difficulty:'level1',scope:'svet',type:'tiebreaker'},
{id:9006,question:'V ktorom roku sa skončila 2. svetová vojna?',answer:'1945',category:'dejiny_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9007,question:'Koľko hráčov hrá na ihrisku v hádzanej?',answer:'7 (vrátane brankára)',category:'sport_sk',difficulty:'junior',scope:'sk',type:'tiebreaker'},
{id:9008,question:'Aká je najmenšia krajina v Európe?',answer:'Vatikán',category:'geografia_svet',difficulty:'level1',scope:'svet',type:'tiebreaker'},
{id:9009,question:'Koľko centimetrov má meter?',answer:'100',category:'matematika_sk',difficulty:'junior',scope:'sk',type:'tiebreaker'},
{id:9010,question:'V ktorom meste sa nachádza Eiffelova veža?',answer:'Paríž',category:'zaujimavosti_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9011,question:'Aké je hlavné mesto Slovenska?',answer:'Bratislava',category:'krajske_mesta',difficulty:'junior',scope:'sk',type:'tiebreaker'},
{id:9012,question:'Koľko dní má rok?',answer:'365 (alebo 366 prestupný)',category:'matematika_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9013,question:'Aká farba vznikne zmiešaním modrej a žltej?',answer:'Zelená',category:'zaujimavosti_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9014,question:'Koľko strún má gitara?',answer:'6',category:'hudba_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'},
{id:9015,question:'Kto namaľoval Monu Lízu?',answer:'Leonardo da Vinci',category:'umenie_svet',difficulty:'junior',scope:'svet',type:'tiebreaker'}
];
